remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: TAMAKO的个人网站
description: 对这个世界和自我的探索方式之一.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
